### ISSUE TITLE
View user's account

### ISSUE THREAD

**Issue by araqueheinz** [fs-tech-degs/capstone-araqueheinz#2]
As a user, I want to be able to create & view my account.

**Comment by araqueheinz** [comment]
# Functional Requirements

1. Critical Requirements

- [ ] The user has the ability to edit his/her account.
- [ ] The user has the ability to follow topics they will like to see on their feed.
- [ ] The user has the ability to see users past content and debates.

2. Minor Requirements

- [ ] The user has the ability to cancel/delete THEIR account.
- [ ] The user has the ability to FOLLOW USERS FROM THEIR ACCOUNT
- [ ] The user has the ability to SEE WHO FOLLOWS ANOTHER USER

**Comment by brandonbrown** [comment]
Brandon says change the headers!
